[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:backend"]

[start]
cmd = "npm run start:backend"

[variables]
NODE_ENV = "production"
